<?php

function ProjectTheme_add_pesapal_deposit($uid = '')
{
	
				$ProjectTheme_pesapal_enable = get_option('ProjectTheme_pesapal_enable');
				if($ProjectTheme_pesapal_enable == "yes"):
				
				?>
                
                
                <strong><?php _e('Deposit money by PesaPal','pt_gateways'); ?></strong><br/><br/>
                
                <form method="post" action="<?php bloginfo('siteurl'); ?>/?p_action=pesapal_deposit_pay">
                <?php _e("Amount to deposit:","pt_gateways"); ?>  <input type="text" size="10" name="amount" /> <?php echo projectTheme_currency(); ?>
                &nbsp; &nbsp; <input type="submit" name="deposit" value="<?php _e('Deposit','pt_gateways'); ?>" /></form>
    			<br/><br/>
                <?php endif; 
	
}


function ProjectTheme_pesapal_deposit_show()
{
	
	global $wp_query, $wpdb, $current_user;
	$amount = $_POST['amount'];
	get_currentuserinfo();
	$uid = $current_user->ID;
	//----------------------------------------------
		 
	$tm = time();
	$title_post = 'Deposit Cash';

	//---------------------------------
	
	$tm 			= current_time('timestamp',0);
	$currency 		= get_option('ProjectTheme_currency');
	
	//https://www.payfast.co.za/eng/process
	//=======================================================================
	
	include('oauth.php');

 
		$token = $params = NULL;
		$consumer_key = get_option('ProjectTheme_pesapal_key');//Register a merchant account on
						   //demo.pesapal.com and use the merchant key for testing.
						   //When you are ready to go live make sure you change the key to the live account
						   //registered on www.pesapal.com!
		$consumer_secret = get_option('ProjectTheme_pesapal_secret');// Use the secret from your test
						   //account on demo.pesapal.com. When you are ready to go live make sure you 
						   //change the secret to the live account registered on www.pesapal.com!
		$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
		$iframelink = 'https://www.pesapal.com/API/PostPesapalDirectOrderV4'; //http://demo.pesapal.com/api/PostPesapalDirectOrderV4';//change to      
						   //https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you are ready to go live!	
						   
		if(get_option('ProjectTheme_working_mode') == "test") 	$iframelink = 'http://demo.pesapal.com/api/PostPesapalDirectOrderV4';			   
						   
		$prs = $uid.'|'.$tm;
		$prs_id = $uid.$pid.$tm.rand(0,99);
		update_option('prs_pesa_' . $prs_id, $prs);
						   
		//get form details<br>$amount = $_POST['amount'];
		$amount 		= number_format($amount, 2);//format amount to 2 decimal places
		update_option('amnt_pesa_' . $prs_id, $amount);
		$desc 			= $title_post; //$_POST['description'];
		$type 			= 'MERCHANT'; //$_POST['type']; //default value = MERCHANT
		$reference 		= $prs_id; //$_POST['reference'];//unique order id of the transaction, generated by merchant
		//$first_name 	= $_POST['first_name']; //[optional]
		//$last_name 		= $_POST['last_name']; //[optional]
		$email 			= $current_user->user_email; //$_POST['email'];
		//$phonenumber 	= ''; //ONE of email or phonenumber is required
		
		$callback_url = get_bloginfo('siteurl') . '/?redirect_pesapal=1'; //redirect url, the page that will handle the response from pesapal.
		$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchemainstance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" xmlns=\"http://www.pesapal.com\" />";
		$post_xml = htmlentities($post_xml);
		
		$consumer = new OAuthConsumer($consumer_key, $consumer_secret);
		//post transaction to pesapal
		$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET",
		$iframelink, $params);
		$iframe_src->set_parameter("oauth_callback", $callback_url);
		$iframe_src->set_parameter("pesapal_request_data", $post_xml);
		$iframe_src->sign_request($signature_method, $consumer, $token);
		
		
		
?>

<iframe src="<?php echo $iframe_src;?>" width="100%" height="620px" scrolling="auto" frameBorder="0"> <p>Unable to load the payment page</p> </iframe>

<html>
<head><title>Processing PesaPal Payment...</title></head>
<body onLoad="document.frmPay.submit();" >
<center><h3><?php _e('Payment by PesaPal', 'ProjectTheme'); ?></h3></center>
</body>
</html>

<?php	
}

?>